### ISSUE TITLE
Windows Google Drive sync to network share

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11703]
> **a263ef1** created the issue

Hi guys,

I recently updated to 7.9.1.

I am trying to sync a Google Drive to a Windows share. When I hit sync, I get this error:

```
[Window Title]
Error

[Main Instruction]
Error

[Content]
Object must be a root directory ("C:\") or a drive letter ("C").

```

It seems to dislike the selection of the network location (\\server\share\folder) as a destination, however this worked fine on 6.8.2.

Any ideas?

**Comment by dkocher** [comment]
Duplicate for #5330.

**Comment by galapogos01** [comment]
Hi guys,

I opened this as I could not get Download To... to work with a UNC share after version 6.8.2. It's been closed as a dupe, but I don't think it is.

Recently 6.8.x stopped working with Google Drive altogether due to the authentication mechanism deprecating on the Google end. So now I have to upgrade, and the bug isn't fixed, so I can no longer sync Google Drives to a UNC share.

Is there any way to sync to a UNC share (ie. NAS etc) or am I looking at finding another file transfer tool?
