### ISSUE TITLE
v7.10.1 sftp fails, resume copies 141% (i.e. copies more than size of original file)

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11772]
> **b1c4830** created the issue

a file less than 1Gb on sftp source, ends up 1.2 Gb  on local destination.

Any logs I can enable to report this properly? Ended up copying via WinSCP successfully in a fraction of the time.

**Comment by capekasa** [comment]
Is happening for years over years and it won't be fixed with Cyberduck. Programmer can't see problem so he ignores. Happenes with pure FTP also. all other programs work fine like Transmit on Mac. 
Maybe happening on multiple reconnections/resumes only?
<img width="640" alt="Bildschirmfoto 2021-12-10 um 15 45 35" src="https://user-images.githubusercontent.com/40778297/145651865-093f3cf5-016b-4bc0-a4ed-ee1409ba5a23.png">
.

**Comment by dkocher** [comment]
Duplicate for #13374.
