### ISSUE TITLE
Unable to change storage class of file in vault

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11830]
> **186d225** created the issue

Hallo, ich habe Daten in einem Cryptomator Vault in einem Scaleway Bucket
hochgeladen.
Dieses anschließend in die Speicherklasse Glacier verschoben.

Wenn ich nun eine Datei daraus herunterladen möchte und über die
Dateiinformationen die Klasse auf Standard ändern möchte erhalte ich von
Cyberduck den Fehler:

```
Your proposed upload exceeds the maximum allowed object size. Please
contact your web host for further assistance.
```

Die Datei ist jedoch nur knapp 4 MB groß.
Der Scaleway Support verweist auf Cyberduck.
___
Attachments

* [`Screenshot 2021-10-15 at 11.22.25.png`](https://github-cyberduck-assets.s3.amazonaws.com/11830/Screenshot%202021-10-15%20at%2011.22.25.png) (82.2 KiB)

**Comment by blu-e-man** [comment]
Hello, I was the creator of this error in the other platform. 
I would like to give an update. 

With Scaleway Support and their Advanced Team it took me two months (!) to manually transfer data from Glacier to Standard class.
Neither via the CLI nor via the GUI the data could be transferred to Standard. 

Unfortunately, support did not communicate where the problem was or is. Therefore, I assume that the error is on the part of Scaleway, since their systems do not work cleanly and do not execute the commands again CLI.
