### ISSUE TITLE
Unable to Upload anything over 100mb to Google Drive

### ISSUE THREAD

**Issue by mvjunkie** [iterate-ch/cyberduck#12744]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**

**Expected behavior**
Being able to upload large files, usually 50gb+, been using Cyberduck for a long time now and this issue just started a few days ago. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1
![Screenshot_20220105-061444_Remote Desktop](https://user-images.githubusercontent.com/97169193/148217886-64c4812c-0cfb-41eb-8590-02c61013f62a.jpg)

**Log Files
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/7814837/cyberduck.log)
**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**
I have used CD for a long time now and never had any issues until now. Anytime i attempt to upload a large file, I get socket write errors, I even tried mountain duck, and they still fail with MD. I have absolutely no idea what is going on. I have already Spoken to Google about my drive account and they have checked everything out and its working on their end. I have spoken to 2 reps from Google and 1 escalations department manager and they say my account is fine. I am able to upload these large files via the web browser on google drives website, but thats it. All CD uploads fail. ( I have tried browser connection, single connection, and multi, all with the same result, the upload starts, then keeps failing and starting the upload over until it finally displays a socket error )

Please help,

Thank you
Rob

**Comment by AliveDevil** [comment]
```
2022-01-05 03:11:46,107 [timer-1] DEBUG ch.cyberduck.core.transfer.TransferAdapter - TransferProgress{size=82978066791, transferred=3182210740, progress='3.0 GiB (3,182,210,740 bytes) of 77.3 GiB (3%, 2.9 MB/sec, 7.5 hours remaining)', speed=2921.3649821121853}
2022-01-05 03:11:46,193 [rcVtK4gt-transfer-5] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.ConnectionRefusedException, file=null, message='Connection failed', detail='Connection reset by peer: socket write error.', cause='java.net.SocketException: Connection reset by peer: socket write error'}
2022-01-05 03:11:46,195 [rcVtK4gt-transfer-5] DEBUG ch.cyberduck.core.Session - Connection did close to Host{protocol=Profile{parent=googledrive, vendor=iterate GmbH, description=null, image=null}, port=443, hostname='www.googleapis.com', credentials=Credentials{user='mvjunkie@ltddistributions.science', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=null}, uuid='69ea0b24-4c47-4965-a659-ddc349448a54', nickname='null', defaultpath='null', workdir=null, labels=null}
```

Do you know whether your ISP performs forced-disconnects to refresh leased ip addresses?
Your router may have resource limitations, which forces it to recycle old TCP connections, thus closing the upload.
Is your router or firewall configured to close TCP connections after a certain amount of time? The transfer started at around 2:54, and failed at around 3:11, giving a 17 minute transfer.
Cyberduck is performing a single TCP connection stream to Google Drive, without uploading small parts.

I just tried uploading a 250 MB file, and it went through fine.

**Comment by mvjunkie** [comment]
I am honestly not sure. How would I check? The setup has not changed from when it used to work, I used to transfer terabytes worth of data with CD, just left it running 24/7 uploading using a browser connection in the settings. I have Comcast/Xfinity and am directly hard wired into their Gateway/Router ( again same setup as before ), using an Comcast XB7 modem. I had to select this modem to be able to get unlimited data with no caps. So, while its the same setup and for a long while it use to work, now its force closing sessions, im not sure what to do. Replace the modem?

**Comment by AliveDevil** [comment]
Can you check whether uploading at day-time (not at 2 in the morning) makes any difference at all?

Run a constant ping-test against the DNS-server of comcast (`ping 68.87.85.102`, or on Windows: `ping -t 68.87.85.102`) and check for possible packet-loss between 2am and 4am. Hitting Ctrl+C at the end will bring up a statistic of packages sent, mean round trip time and packages lost.

If it worked before, did the Xfinity Gateway upgrade its software automatically (I know my router from Telekom Germany does)? Eventually you can get some hints from the [my device info portal](http://mydeviceinfo.xfinity.com/) or the [equipment update page](https://customer.xfinity.com/devices/equipment-update) provided by comcast.

Another option would be to check whether an older version of Cyberduck works fine, can you remember which version worked and downgrade to that using the installer on the [changelog page](https://cyberduck.io/changelog)?

Ruling out possibilities here:
* Comcast alters connections (though they shouldn't anymore, since 2008), and resets TCP connections
* The Xfinity router did an upgrade, and is now having issues keeping up with uploads, or has some feature enabled that interferes with long running TCP connections
* Comcast does an IP refresh in the night, interrupting the connection
* A Cyberduck updated introduced the issue

While writing I got a total of 2.2 GiB transferred to Google Drive, without interruption.

**Comment by mvjunkie** [comment]
I've determined it is my ISP Comcast, I am not totally sure where the fault is, I will run some of the tests you mentioned above to try to determine what is going on. I went to my brother's house an hour away who has 2 gig fiber symmetrical, I was able to upload at almost 1 gig/sec to Google Drive no problem using CD. After some research, they took down the network last night for 3 hours,  stating on their website they noticed performance issues in my area, at 11:30am I received a text saying the maintenance was over and services are back up, however I still am unable to sustain an upload unless I use the web gui or Google Drive for desktop. I usually always used CD because I like the checksum verification it does with uploads and downloads. This really is a bummer until I can figure out where on the internet path it breaks down.
