### ISSUE TITLE
Can't delete download cache in cyberduck -> crashes

### ISSUE THREAD

**Issue by e5cwer3** [iterate-ch/cyberduck#12791]
Hi,

I know that due to never deleting the download list in Cyberduck (my own lame fault, I know), the app now constantly crashes whenever I try to open the transfer list. This renders me unable to delete all the downloads.

I don't seem to have any cache folder in my cyberduck repo either? This is rather confusing for me on what I could do.

I've tried deleting, reinstalling, older versions / newer versions, and so on.

Somehow it is still cached somewhere (as my previous installments of saved passwords / servers is still on there after reinstalling), but I just can't seem to find it how / where.

Please bare in mind that I am rather new to working in IT, so I don't have the most knowledge, so bare with me please.

Thank you so much in advance,

Kind regards,

T.

**Comment by AliveDevil** [comment]
I assume you are running on Windows.

There are two workarounds for now:
* Increase the GDI User Object Handle limit
* Clear the transfers list manually

**Increase the GDI User Object Handle**
Check `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows\` and increase `USERProcessHandleQuota`.

**Delete transfers list manually**
Navigate to the application support folder[^1] (`%AppData%\Cyberduck`) and rename the folder `Transfers` to `Transfers.bak`. Now Cyberduck should work again.
If deleting the transfers list works I'd like to get a copy of the transfers folder in order to reproduce the issue here, if possible. Please send them as zipped attachment to support@cyberduck.io, and mention this ticket.

[^1]: https://docs.cyberduck.io/cyberduck/support/#application-support-folder

**Comment by e5cwer3** [comment]
Renaming the transfer folder did help. Thank you so much. I'll send the zipped file to you. 

(You assumed right with the Windows thing )

**Comment by tatze96** [comment]
duplicates #15885
