### ISSUE TITLE
"Interoperability failure" error on TLS 1.1-only server

### ISSUE THREAD

**Issue by arencambre** [iterate-ch/cyberduck#12852]
Starting just recently, Cyberduck gives our users an "Interoperability failure" error when connecting to a Windows 2012 R2 server using FTP-SSL. Cyberduck worked fine against this server for years.

The server currently supports TLS 1.1 as its highest version. We're suspecting that Cyberduck silently dropped TLS 1.1 support. We're going to add TLS 1.2 support later today to see if that restores connectivity.

We're reproducing this error on Windows and Apple computers with the current release (version 8.2.1 (36773)).

I have a user with Cyberduck 7.9.1 (34974) installed. He is able to connect with that. He updated to the most recent release, and now he gets the same error.

It is merely my theory that Cyberduck dropped TLS 1.1 support. If it did, that fine since TLS 1.1 is not secure. I just ask that you confirm if that is true so we can be assured we're addressing this in the right way. Also, if it is dropped, please be sure to add this to a changelog or product documentation so that determine this better in the future.

**Comment by dkocher** [comment]
As of ed4a6b96 TLS 1.1 should still be supported.

**Comment by arencambre** [comment]
OK. Let me follow up later once we've added TLS 1.2 to the server.

To this point, I have no theory to explain this other than that Cyberduck no longer supports TLS 1.1.

**Comment by arencambre** [comment]
I wonder if you use a library that dropped or reduced support for TLS <1.2?

**Comment by arencambre** [comment]
Yeah, I see OpenJDK DLLs on Windows, and I assume you use those on the Apple version, too? If so, there's a lot of language in the OpenJDK issue tracker and elsewhere about OpenJDK dropping support (entirely or by default?) for TLS <1.2.

**Comment by AliveDevil** [comment]
> As of [ed4a6b9](https://github.com/iterate-ch/cyberduck/commit/ed4a6b963d5f75f2e9b6fef72dc0cf4518fef31c) TLS 1.1 should still be supported.

This is about FTP, not regular HTTPS, which is configured to allow up to TLS1.3
FTP is configured to allow TLS 1.2, 1.1 and 1.0 (that is SSLv3-equivalent), due to incompatibility with TLS1.3 on FTP servers: https://github.com/iterate-ch/cyberduck/commit/c0524b78d7ade006f356824571c2fbd3e3ffa8bc

I thought I tested this on Windows after the IKVM update, and I thought it worked.

**Comment by AliveDevil** [comment]
> Yeah, I see OpenJDK DLLs on Windows, and I assume you use that on the Apple version, too? If so, there's a lot of language in the OpenJDK issue tracker and elsewhere about OpenJDK dropping support (entirely or by default?) for TLS <1.2.

Cyberduck doesn't run on .NET Framework on macOS, and uses just plain old Java (JDK 18), while on Windows we are limited to Java 8, which we just recently upgraded from JDK 8u45 to JDK8u312, which, besides adding TLS1.3 support, might have broken other parts, we just didn't discover yet.
So macOS run on JDK 17, while Windows is using a transpiled version of JDK8 on .NET Framework.

**Comment by arencambre** [comment]
> So macOS runs on JDK 17, while Windows is using a transpiled version of JDK8 on .NET Framework.

Just to be clear, I am seeing OpenJDL, not (Oracle) JDK:
![image](https://user-images.githubusercontent.com/411495/152543789-b870a26d-5262-46ed-a8e1-7271a995be0a.png)

**Comment by arencambre** [comment]
This suggests OpenJDK dropped TLS 1.1 and 1.0 support (the right thing to do!) in late 2020 in version 16: https://bugs.openjdk.java.net/browse/JDK-8254713

**Comment by AliveDevil** [comment]
> Just to be clear, I am seeing OpenJDK, not (Oracle) JDK:

Correct, but it is _not_ OpenJDK, nor any other JDK - in the sense, that it is Java. It is the (OpenJDK) Java sources transpiled for the .NET Framework, running on the .NET Framework, instead of running on Java.

Unless Oracle backported the TLS1.1 and TLS1.0 deprecation onto JDK 8 it should work fine on Windows, and we have an issue in our Java to .NET conversion step.

**Comment by arencambre** [comment]
> Unless Oracle backported the TLS1.1 and TLS1.0 deprecation onto JDK 8 it should work fine on Windows, and we have an issue in our Java to .NET conversion step.

It may not be Windows only. We have an Apple user with the same "cannot connect to the server" problem. Let me see if that person can connect now. I'll report back.

**Comment by AliveDevil** [comment]
So macOS and Windows are using different Java-environments (8 and 17).
On macOS with Java 16 TLSv1 and TLSv1.1 got disabled, which is why you are seeing the connection issues on macOS.

On Windows we updated Java from Java 8u45 to Java 8u312 which includes a change (refer to openjdk HG link above) to also disable TLSv1 and TLSv1.1, which is why you are seeing this there as well.

This is curtesy of the OpenJDK community deciding to disable TLSv1 and TLSv1.1 in older releases of Java (breaking change on JDK8).

Possibly link to Javas "Crypto Roadmap" for future reference, and keeping an eye on it, in case Oracle decides to make breaking changes, again: https://java.com/en/jre-jdk-cryptoroadmap.html

**Comment by arencambre** [comment]
Confirming that the Apple user can now connect to the server using FTP-SSL. This affirms other comments above that Cyberduck does not support TLS 1.1.

**Comment by AliveDevil** [comment]
Closing as decided to not support TLSv1 and TLSv1.1 in the future.

We are going to document this in our docs, see linked ticket in iterate-ch/docs#150.
