### ISSUE TITLE
AWS SSO - Calculated hash for cached credentials does not match actual cached credentials filename

### ISSUE THREAD

**Issue by georgematthew** [iterate-ch/cyberduck#12890]
**Describe the bug**
When attempting to use AWS Single Sign On credentials with Cyberduck (added in [a310196d02f378a8ac31bfaaec8fca40b0316a1e](https://github.com/iterate-ch/cyberduck/commit/a310196d02f378a8ac31bfaaec8fca40b0316a1e)), the file name SHA1 hash computed by Cyberduck does not match the file name on my local machine and Cyberduck throws an error: 
![image](https://user-images.githubusercontent.com/35472284/154083486-621c0f85-7c87-421c-9bc8-7242fe430d41.png)

**To Reproduce**
1. Set up an S3 (Credentials from AWS Security Token Service) connection with AWS Single Sign On (SSO) with a valid SSO profile.
2. Attempt to open the S3 connection.

**Expected behavior**
Cyberduck should calculate the correct hash value for the SSO cached credentials and use these credentials to set up the S3 connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/35472284/154085065-4b081f1c-5fda-412c-9b06-b4a79c36c4bb.png)
![image](https://user-images.githubusercontent.com/35472284/154083486-621c0f85-7c87-421c-9bc8-7242fe430d41.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19044.1469
 - Version Cyberduck 8.2.4 (36910)

**Additional context:**
I have attempted this with named SSO profiles as well as a "default" SSO profile with the same results.

**Comment by jsw1993** [comment]
It's also looking in the wrong folder for the json.

> 2022-02-17 11:31:32,999 [background-14] DEBUG ch.cyberduck.core.sts.STSCredentialsConfigurator - Attempting to read SSO credentials from D:\Users\james.williams2\.aws\cli\cache\4e7f23734635206c83786a71083fdeee5b87b752.json

V2 of the AWS CLI appears to use ~/.aws/sso/cache

**Comment by georgematthew** [comment]
Hi @yuzawa-san, thanks for checking this out. I'm running AWS CLI version 2.4.17, and I have not been able to get the SSO functionality working.

@jsw1993 You make a great point. I wasn't paying attention to the directory, but my logs show the same. Cyberduck is looking for `C:\Users\user\.aws\cli\cache\<hash>.json` while the credentials are actually located at `C:\Users\user\.aws\sso\cache\<hash>.json`

**Comment by yuzawa-san** [comment]
OK I think I may need to add some more documentation here, since I believe a manual step is required with the CLI to populated the right cache. I'm running CLI 2.4.10 and can report the following behavior. I have cleared both cache directories.

* I run `aws sso login` (or optionally with a profile `aws sso login --profile myProfile`) which populates `~/aws/sso/cache` with some client secrets, but no usable AWS credentials.
* I then need to use the CLI to seed the second cache in `~/aws/cli/cache` which actually contains the credentials and which Cyberduck actually reads from. I typically do this by running `aws sts get-caller-identity` (or optionally with a profile, the same profile as in the first step `aws sts get-caller-identity --profile myProfile`
* Use Cyberduck successfully

Does this work for you?

I suppose this could be added to the documentation. Alternatively, the application could try to execute `aws sts get-caller-identity` but that seems a bit dirty to subprocess given how everybody's python installations are different. Once again, upgrading the S3 SDK to a version which supports SSO by default is bigger task. I don't know what that would entail. I don't currently have the time to take on such a project, but I could assist the very minimum to determine the feasibility. Could we put both the old SDK and the new SDK on the classpath? I've done that in the past with little issues.

**Comment by dkocher** [comment]
Documentation should be added to https://docs.cyberduck.io/protocols/s3/#aws-single-sign-on. I have reopened iterate-ch/docs#97.
