### ISSUE TITLE
Odd error state related to saving files

### ISSUE THREAD

**Issue by aardWolf64** [iterate-ch/cyberduck#12914]
I use Cyberduck pretty extensively when I am editing PHP files on our server.  I double click the file to open it in BBEdit on my Mac.  I make some changes, hit CMD-S to save the file, then check out the results in the web browser after it uploads.

Occasionally when I've been editing a file for a while, instead of the filename BBEdit will show the filename plus the date at the end (so "test.php" becomes "test.php 02/22/2022").  As soon as that happens, Cyberduck stops uploading the file when I save it.  The only way to recover from this is to quit Cyberduck and BBEdit, reopen Cyberduck, and reconnect.  I'm wondering if BBEdit or Cyberduck is at fault here, so I'll be entering a similar bug with the BBEdit people.

**Comment by AliveDevil** [comment]
Can you check whether BBEdit uses atomic saves?

That is
* create a temporary file
* save to that file
* rename the original file
* rename the temporary file to the original file name

Cyberduck only monitors the original file. When that is (re-)moved Cyberduck loses track and never recovers from this.

**Comment by AliveDevil** [comment]
A Cyberduck macOS developer needs to check in here.
Technically the directory the file resides in is being watched: https://github.com/iterate-ch/cyberduck/blob/master/core/dylib/src/main/java/ch/cyberduck/core/editor/FSEventWatchEditor.java#L58, which is the correct way of monitoring for atomic saves on macOS: https://stackoverflow.com/a/26567779

**Comment by aardWolf64** [comment]
I just encountered the issue again today, after making several edits to a file named “cayuse.php”.  The filename in BBEdit is now “cayuse.php 15-06-14-582.php”.  I thought I remembered it being a date, but that doesn't look like the case.

**Comment by siegel** [comment]
> Can you check whether BBEdit uses atomic saves?

BBEdit does not, by default. There is an expert preference to enable atomic file saves, but this is off by default, and the user would have to have explicitly turned it on with a suitable `defaults write` command.

However, unless the user's described behavior occurs *every time* they save a file, I suspect that atomic writes wouldn't be an issue.

If Cyberduck is using kevents or a similar mechanism (`DISPATCH_SOURCE_TYPE_VNODE`, for example) to watch the file, then perhaps Console logging filtered on the file name in question would tell the tale, since presumably something is happening at the file level to cause Cyberduck to lose track. (That doesn't make it Cyberduck's fault; but presumably _something_ is going on.)

**Comment by siegel** [comment]
Incidentally: looking over some old support tickets, it looks like we have sporadic reports of this issue going back to early 2020.

The common symptom appears to be that the backing file (that Cyberduck downloaded and asked BBEdit to open) is getting moved to the trash. This is something that BBEdit will not ever do spontaneously; but we have never found any clear indicator as to how it is happening.

If there's some condition in which Cyberduck decides that the backing file needs to be moved to the trash, perhaps it's worth investigating  what triggers this (and whether it's reproducible).

**Comment by AliveDevil** [comment]
> sporadic reports of this issue going back to early 2020.

First ticket in our internal tracker is dated 2016, while Trac (now moved to Github) first found traces in 2006[^1].
We use `FSEventStreamCreate` for filesystem events[^2].

@aardWolf64 Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), then perform your regular steps until you see an erroneously named file uploaded and send us the log file you can reach on that same tab. If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-12914 to support@cyberduck.io, otherwise attach here.

[^1]: https://github.com/iterate-ch/cyberduck/issues?q=is%3Aissue+BBEdit+sort%3Acreated-asc
[^2]: https://github.com/iterate-ch/cyberduck/blob/master/core/dylib/src/main/java/ch/cyberduck/core/io/watchservice/FSEventWatchService.java#L101

**Comment by aardWolf64** [comment]
I've enabled debug logging, and will continue to use the software as I usually do tomorrow.  I typically only see it once or twice a week, so it may take a while to reproduce.

**Comment by cculver4** [comment]
I encountered the error again.  I'm sending the zipped log file now.

**Comment by AliveDevil** [comment]
Internal Ticket Reference: 9642

**Comment by dkocher** [comment]
Duplicate for #11729.
