### ISSUE TITLE
No files showing up

### ISSUE THREAD

**Issue by owenjohnsonlegit** [iterate-ch/cyberduck#12982]
No matter how many times I try, when I connect my account, nothing shows up at all. It says that it's at the root file but still "0 items". I know this isn't the case because my website has files in it that I had to upload individually through the web host. I am using an M1 MacBook Air.

**Comment by tatze96** [comment]
Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), try to connect to the server, and send us the log file right after there are no files visible again? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-12982 to support@cyberduck.io, otherwise attach here.

Additionally, we need to know which protocol you use.

**Comment by owenjohnsonlegit** [comment]
I think it was blue host. I switched my web hosting over to site ground and now cyberduck works great!
