### ISSUE TITLE
Symlink not visible issue and 550 error

### ISSUE THREAD

**Issue by retanray** [iterate-ch/cyberduck#13050]
Please understand that it may look a bit strange using a translator.

In some FTP servers, the folder created as a symbolic link is not visible, and a 550 error occurs when directly moving to the folder.

In other programs such as filezilla or coda, it looks normal, and you can access the folder.

I'm wondering if these errors are a problem with a specific server or a program problem

**Comment by PorkLip** [comment]
I'm not sure this is the same issue but I have just noticed that folders that are symlinks can be opened but they fail to show any content in the folders. I'm using a SFTP connection. Might this be the same issue?

**Comment by affiwtaoe** [comment]
In my case, there is no problem in displaying and accessing the symbolic link on servers using sftp, but when using ftp, the symbolic link is not displayed and access is not possible when moving directly to the folder path :(

**Comment by tatze96** [comment]
I can reproduce the initially described FTP issue but this is caused by the server configuration. Please verify that your server configuration allows you to display and access symbolic links.

Regarding the SFTP issues:
I wasn't able to reproduce the described SFTP symlink issues and they don't seem to be the same issue. Please open an additional ticket preferably with information on your used server software if the behavior still occurs.
