### ISSUE TITLE
Bug in connecting to several servers

### ISSUE THREAD

**Issue by EduardoBrag** [iterate-ch/cyberduck#13302]
Hi! I have some client server that simply won't connect to the server, I tried a different app called CrossFTP and solved the problem, but to earn my money buying Cyberduck this issues must be solved :)

**Comment by tatze96** [comment]
Hi,

Please share the following information for further investigation:
- Which protocol is in use?
- Are there any error messages? If yes, send us screenshots.
- Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), try to connect to the server, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-13302 to support@cyberduck.io, otherwise, attach it here.

– Laura

**Comment by EduardoBrag** [comment]
Hi Laura!

Sorry I’m not very familiarized with all of the procedures, regarding to the last point there :)

Let me show you if this helps See bellow.

I am sending you also a 3rd party app that is configured with the same data server connection etc. and Its logged on and Cyberduck won’t connect. 

Thanks

**Comment by tatze96** [comment]
Can you re-attach the email attachments through the GitHub web interface to this ticket? GitHub doesn't add email attachments to the ticket itself which is why they aren't visible to us.
