### ISSUE TITLE
ftp upload

### ISSUE THREAD

**Issue by jaennert** [iterate-ch/cyberduck#13310]
Der Upload eines kompletten Ordner mit mehreren Unterverzeichnissen und einzelnen Dateien auf einen Server brach immer wieder ab und verlangte ein neues Login. Nach mehreren Versuchen reagierte Cyberduck 8.3.2 nicht mehr und musste unter MacOS zwangsweise beendet werden. Der Transfer mit einem alten Transmit 4.4.13 war ohne Probleme möglich.

**Comment by tatze96** [comment]
Assuming that you are using FTP, this is possibly caused by running against the maximum number of concurrent connections to your server.

There are multiple ways to solve or work around this issue:
- Choose "Open single connection" or "Use browser connection" instead of "Open multiple connections" within the dropdown menu in the Cyberduck preferences *Transfers* tab.
- Switch to another protocol like SFTP or WebDAV if possible.
- Reach out to your server administrator to increase the maximum number of concurrent connections to the server.

– Laura

**Comment by dkocher** [comment]
Duplicate for #13322
