### ISSUE TITLE
Cyberduck - crashing on repeated use of 'download to'

### ISSUE THREAD

**Issue by samatrelative** [iterate-ch/cyberduck#13325]
Using the 'download to' menu, repeatedly leads to a not fully populated download to menu box for folder choice, then ultimately to just crash the programme entirely.
Version 8.3.2 (37449)

**Comment by AliveDevil** [comment]
Don't see it here on macOS or Windows.
Which OS are you running on? Which protocol are you using?

**Comment by samatrelative** [comment]
Hi,

Windows:
Edition Windows 10 Home
Version 21H2
Installed on ‎25/‎02/‎2021
OS build 19044.1645
Experience Windows Feature Experience Pack 120.2212.4170.0

SFTP protocol

Thanks,

Sam

**Comment by tatze96** [comment]
I can't reproduce the described behavior on my side within the latest Snapshot Build (8.3.4) of Cyberduck.
Please send us the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) for further investigation.

**Sidenote**: Make sure to attach the crash report through the GitHub web interface as it wouldn't be visible to us otherwise.

– Laura
