### ISSUE TITLE
Listing Directory failed | Stream closed. The connection attempt was rejected. The server may be down, or your network may not be properly configurated.

### ISSUE THREAD

**Issue by ricapag2409** [iterate-ch/cyberduck#13343]
I'm facing an issue using Cyberduck, if i stay away from Cyberduck for about 30 seconds or more editing an file, the connection close and i was unable to reconnect again, my solution to solve this is close Cyberduck and open again, i installed the 8.2.3 version released on 04 Feb 2022, and it works perfeclty.

Screenshot attached in this thread.

![CyberduckError](https://user-images.githubusercontent.com/99998824/165958294-7f84dd6e-c3dc-4282-aef0-d6199f7431d6.png)

**Comment by tatze96** [comment]
I can't reproduce the described behavior within the latest Snapshot Build (8.3.4) of Cyberduck. I've tested the protocols WebDAV, SFTP, and FTP on my side. Does the behavior persist within the latest Snapshot Build?

If the behavior persists we would need the following information:
- Which protocol is in use?
- Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), reproduce the described behavior, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-13343 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log file here make sure to attach them through the GitHub web interface as they wouldn't be visible to us otherwise.

– Laura

**Comment by dkocher** [comment]
Duplicate for #13728.
