### ISSUE TITLE
(En Français) Changer de compte Hubic

### ISSUE THREAD

**Issue by RBeauto** [iterate-ch/cyberduck#13363]
Bonjour

Je me suis servi de Cyberduck pour récupérer les fichiers d'Hubic qui va disparaitre.

Sur 2 comptes ça va mais il semble bloqué pour les 2 autres que j'ai.

comment faire ?

Merci pour votre réponser

**Comment by tatze96** [comment]
Hi,

To investigate this further we'll need the following information:
- Please send us screenshots of the error message if there are any.
- Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), reproduce the behavior on one of the 2 affected accounts and send us the log file afterward? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-13363 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the screenshots and the log file here make sure to attach them through the GitHub web interface as they wouldn't be visible to us otherwise.

– Laura

**Comment by RBeauto** [comment]
Issue #13363

Bonjour

    Pour approfondir cette question, nous aurons besoin des informations suivantes:

    Veuillez nous envoyer des captures d’écran du message d’erreur s’il y en a.

Il n'y a pas de message d'erreur

    Pouvez-vous activer la journalisation de débogage, reproduire le comportement sur l’un des 2 comptes affectés et nous envoyer le fichier journal par la suite? Si vous ne souhaitez pas que les données sensibles soient partagées publiquement, veuillez envoyer le fichier journal avec la référence du ticket GH-13 363 à support@cyberduck. io, sinon joignez-le ici.

Je ne trouve pas la journalisation en question.


    Sidenote: Si vous voulez partager les captures d’écran et le fichier journal ici assurez-vous de les joindre via l’interface web de GitHub car ils ne seraient pas visibles autrement.

Rémi

**Comment by Cassie205** [comment]
You can reach the log file using the _Show_ button within the Cyberduck preferences _Connection_ tab. The file is called `cyberduck.log`. For additional information please refer to the Cyberduck [documentation](https://docs.cyberduck.io/cyberduck/support/#logging-output).

— Sofie
