### ISSUE TITLE
ftp file dowanload science fiction

### ISSUE THREAD

**Issue by peterpolzin** [iterate-ch/cyberduck#13389]
<img width="634" alt="Screenshot 2022-05-13 at 22 26 36" src="https://user-images.githubusercontent.com/105534470/168412318-5bab97e1-0c73-4cef-ac32-a399aa4091ac.png">
After the last update I cannot download large files - CD is not stopping when 100% filesize reached, still it downloads something over and over again :-). When I press stop and then resume it starts download from the very 0% of the file :-(

**Comment by tatze96** [comment]
Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), reproduce the described behavior, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-13389 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log file here make sure to attach it through the GitHub web interface as it wouldn't be visible to us otherwise.
