### ISSUE TITLE
Opening a SSH Terminal

### ISSUE THREAD

**Issue by Dellow1** [iterate-ch/cyberduck#13390]
Is there a way to open a SSH terminal from the Cyberduck GUI?  I've read about terminal.app but can't find it...

**Comment by AliveDevil** [comment]
For Windows:
Did you check the Windows-tab for [Open in Terminal](https://docs.cyberduck.io/protocols/sftp/#open-in-terminal)?
You can use Go To -> Open in PuTTy or update the toolbar to include the Open in PuTTy action.

On MacOS: You can use Go To -> Open in Terminal or update the toolbar to include Open in Terminal.
Though this doesn't work in the App Store version, due to sandbox limitations.
