### ISSUE TITLE
changing laptops but can't "bring" over the registration?

### ISSUE THREAD

**Issue by 3cstudio** [iterate-ch/cyberduck#13604]
Hi there, I upgraded to a newer laptop and didn't do a full migration of content (since some legacy apps on the old machine won't work in the present version of MacOS). I wondered if there is a way to get Cyberduck to work on the new laptop with the old laptop's credentials? If not, it's no problem to pay for another installation of it on the new computer -- just thought I'd ask. :)
Thanks in advance,
Steve C.
3Cstudio

**Comment by AliveDevil** [comment]
If you purchased through the Mac App Store the license should transfer easily, otherwise you received an e-mail with the donation key after your donation (check your email inbox/archives), or request the donation key associated with your e-mail account you used to donate at [cyberduck.io/help](https://cyberduck.io/help/) if you deleted the e-mail.

If you refer to credentials as login information for your bookmarks: Those are saved in `Keychain Access.app`, exporting and importing a keychain is possible, check the Keychain Access help manual for instructions.

**Comment by 3cstudio** [comment]
Ahhh... yes. I registered it under a different email address years ago -- just had to remember that. :D Thank you!
S
