### ISSUE TITLE
Failure downloading file with segmented download option enabled

### ISSUE THREAD

**Issue by polypx** [iterate-ch/cyberduck#13634]
It's not just me, some of the guys at Native Instruments have had the same issue.  When downloading an .iso with Cyberduck, the process doesn't stop when it reaches the end of the file.  In other words, the download keeps on going and I never have a complete file.  Yesterday for instance, the download reached some 40 GB of a 12 GB file before I cancelled it.

Hopefully you already know about this and a fix is on the way, because I love Cyberduck otherwise.

This is version 8.4.2 on an M1 Mac 12.4

cheers, 
Dan
dan@soniccouture.com

**Comment by tatze96** [comment]
Hi Dan,

I can't reproduce the described download behavior within the latest *Snapshot* version in combination with the SFTP servers available to me.

Please tell us which server software you are using on the server.

Additionally, please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), reproduce the download behavior, and send us the log file afterward. If you don't like to see sensitive data shared publicly, please send the log file with the ticket reference GH-13634 to support@cyberduck.io. Otherwise, attach it here.

**Sidenote**: If you want to share the log file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.

– Laura

**Comment by bertcoerver** [comment]
Hi

I'm having a similar issue (version 8.4.3 on M2 MacOS). Download seem to continue forever and past 100%...

![cyberbug](https://user-images.githubusercontent.com/18460767/189826633-c2596fd7-eb8a-409c-ab86-aff92073bb32.png)

I checked the enable-debug-logging box only after stopping the download, but there seems to be some info in there nonetheless:
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9554137/cyberduck.log)

**Comment by bertcoerver** [comment]
After turning off the "Segmented downloads with multiple connections per file" option, I could download the file. Although once it had finished I think Cyberduck tried to restart the download, asking me if I wanted to overwrite the downloaded file, so I selected "cancel" and the file seems to be okay.

![cyberbug2](https://user-images.githubusercontent.com/18460767/189856511-7b33213f-cb39-48ea-b56b-7cf3647f1229.png)

**Comment by polypx** [comment]
Yes, I've had to turn off the same "segmented downloads" option.  Cyberduck works properly with that option off.

**Comment by dkocher** [comment]
@polypx @bertcoerver Please let us know what SSH server you are connecting to. The SFTP server does possibly not implement reads with a file offset properly.

**Comment by dkocher** [comment]
Duplicate for #13374.
