### ISSUE TITLE
Cannot delete a file

### ISSUE THREAD

**Issue by caitlinsc** [iterate-ch/cyberduck#13632]
We are unable to delete this .png file from the server. I am guessing that the issue may lie with "&amp;" in the file name.

![image](https://user-images.githubusercontent.com/110566358/182696047-7b3c9701-bc50-4abf-9ca3-db57dd055460.png)

**Comment by AliveDevil** [comment]
Out of curiosity: Did you upload a file named `g._passier_&amp;_sohn.png`, or did you upload a file named `g._passier_&_sohn.png`, which then reappeared as the former file?

Currently it looks like somewhere between Cyberduck and your server there has been an encoding issue.
Either the url encoding while uploading went wrong, or the XML encoding in the listing of the file went wrong.

Can you please provide the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) of following procedure:
* Enable Debug Logging
* Click on Show
* Quit Cyberduck
* Delete the previously revealed Log file
* Restart Cyberduck
* Navigate into the folder
* Delete the file
* Quit Cyberduck

If you are not comfortable with sending private data on a public issue tracker send the log file mentioning Github reference 13632 to [support@cyberduck.io](mailto:support@cyberduck.io), otherwise please attach the log file through the web interface of Github, as they don't support e-mail attachments to Github ticket replies.

**Comment by AliveDevil** [comment]
It looks like something is wrong over at Demandware, as we don't see this issue on regular WebDav-servers (Apache, with mod_dav enabled, or Synology Diskstation WebDav).

Can you check with Demandware why the file you uploaded can't be deleted on their end? You can include `DW Request Id hsT6OKoV7WJkAAAK` for them.
If you want us to investigate this further we'd need test credentials on your site to perform a set of transfers to check what is wrong.
