### ISSUE TITLE
Cyberduck grinds computer to a halt/kernel panic when downloading/uploading to a NAS

### ISSUE THREAD

**Issue by jsevakis** [iterate-ch/cyberduck#13793]
Repeatable: downloading and uploading simultaneously to a NAS share grinds my Mac Studio (M1 Ultra) to a halt after several minutes, requiring a hard reboot. (If MacOS notices, it will declare a kernel panic and force a reboot after core 0 does not respond for 90 seconds.)

MacOS 12.6 w/ M1 Ultra, 128 GB RAM, Cyberduck v8.4.5

**Comment by tatze96** [comment]
Is this issue still present within the current Cyberduck release version (8.5.9)?

Could you send us the corresponding system crash report for further investigation if the issue is still present? If you don't like to see sensitive data to be shared publicly, please send the crash report file with the ticket reference GH-13793 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the crash report file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.

**Comment by jsevakis** [comment]
We have stopped using Cyberduck because this issue rendered the app unusable. This bug report was sent over six months ago, so there are no longer relevant system crash logs.
I will download the new version and try again, but in a production environment I cannot test this often so please be patient.
