### ISSUE TITLE
Cyberduck crashes on Mac OS Ventura 

### ISSUE THREAD

**Issue by Aluhut** [iterate-ch/cyberduck#13874]
Hey there,

I upgraded to Mac OS ventura (13.0.1) and Cyberduck (8.5.0) isn't starting. I does make the start animation and closes afterwards.
Could you please help?

**Comment by tatze96** [comment]
Are the crashes on application start still present? If so, please send us the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) for further investigation.

Ensure to attach the crash report file through the GitHub web interface, as it wouldn't be visible to us otherwise.
