### ISSUE TITLE
Issue moving files into folders receiving Access Denied

### ISSUE THREAD

**Issue by ralaya** [iterate-ch/cyberduck#14231]
**Describe the bug**
Receive an error when trying to move files from one folder to another. Using Amazon s3 bucket.

**To Reproduce**
Error is access denied when trying to move files.
Tried to log into preferences and info when trying to move and change permissions for files and folders, no luck.

**Expected behavior**
Be able to move files freely between folders.

**Screenshots**
![image](https://user-images.githubusercontent.com/104936778/218572816-a481f2ad-227d-4df9-84ea-f4452fb500ef.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Received the following message: 
C:\Program Files\Amazon\AWSCLIV2>aws --version
aws-cli/2.9.21 Python/3.9.11 Windows/10 exe/AMD64 prompt/off 
C:\Program Files\Amazon\AWSCLIV2>aws s3api put-bucket-encryption --bucket organization-36b58894-15d3-4775-acb3-37c-s3bucket-c4u4htcqh2ay --server-side-encryption-configuration "{\"Rules\": [{\"ApplyServerSideEncryptionByDefault\": {\"SSEAlgorithm\": \"AES256\"}}]}"
An error occurred (AccessDenied) when calling the PutBucketEncryption operation: Access Denied 
C:\Program Files\Amazon\AWSCLIV2>aws s3api get-bucket-encryption --bucket organization-36b58894-15d3-4775-acb3-37c-s3bucket-c4u4htcqh2ay
An error occurred (AccessDenied) when calling the GetBucketEncryption operation: Access Denied 
C:\Program Files\Amazon\AWSCLIV2>

**Additional context**

**Comment by Cassie205** [comment]
Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), recreate the issue, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly, please send the log file with the ticket reference GH-14231 to support@cyberduck.io, otherwise, attach it here.
**Sidenote**: If you want to share the log file here make sure to attach it through the GitHub web interface as it wouldn't be visible to us otherwise.
