### ISSUE TITLE
Since update, cannot connect

### ISSUE THREAD

**Issue by meatstax** [iterate-ch/cyberduck#14538]
Hello.  
Just applied update to version 8.5.9 (39636).  After update, unable to connect to b2.

This is the log file (repeated endlessly)

```
POST /b2api/v2/b2_list_file_versions HTTP/1.1
Content-Length: 220
Content-Type: application/json; charset=UTF-8
Host: api004.backblazeb2.com
Connection: Keep-Alive
User-Agent: Cyberduck/8.5.9.39636 (Windows 10/10.0.19045.0) (amd64)
Accept-Encoding: gzip,deflate
Authorization: ********
HTTP/1.1 200 
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Content-Length: 1380
Date: Sun, 16 Apr 2023 19:37:58 GMT
Keep-Alive: timeout=5
Connection: keep-alive
POST /b2api/v2/b2_list_file_versions HTTP/1.1
Content-Length: 228
Content-Type: application/json; charset=UTF-8
Host: api004.backblazeb2.com
Connection: Keep-Alive
User-Agent: Cyberduck/8.5.9.39636 (Windows 10/10.0.19045.0) (amd64)
Accept-Encoding: gzip,deflate
Authorization: ********
HTTP/1.1 200 
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Content-Length: 3692
Date: Sun, 16 Apr 2023 19:37:58 GMT
Keep-Alive: timeout=5
Connection: keep-alive
```

**Comment by tatze96** [comment]
The sent log entries don't show unusual behavior. `HTTP/1.1 200` indicates that everything is alright and working correctly.

Please send us the complete log file by following the instructions below.

Verify that [debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level) is enabled, recreate the issue, and send us the log file afterward. If you don't like to see sensitive data to be shared publicly, please send the log file with the ticket reference GH-14538 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.

**Comment by dkocher** [comment]
Possible duplicate of #14527.

**Comment by meatstax** [comment]
Problem resolved. the issue was that the directory was re-populating. I'm assuming that was happening because the update removed previous directory cache.  Sorry to bug yall with it. issue resolved.
