### ISSUE TITLE
Overwrite prompt on download for file already moved to Trash

### ISSUE THREAD

**Issue by KonaBill** [iterate-ch/cyberduck#14694]
Using CyberDuck Mac Version 8.5.9 (39636). Sometimes the app erroneously asks to override an existing file when there is no file.
Steps to reproduce:
1. Assure there is a file within a folder on the Mac.
2. Assure there is a file with the same name on a server. 
3. Drag the file on the Mac to the Trash.
4. Drag the file from the server to the same folder on the Mac.
5. The app erroneously asks if It can replace the file in the folder with the one that is being downloaded, except the file it's asking to replace has already been moved to the Trash. It's as if the Finder hasn't been updated to tag the file as in the Trash, but I've never seen this behavior on any other app.

**Comment by tatze96** [comment]
I can't reproduce the described behavior on my side. Does this issue persist on your side within the latest Cyberduck version?
If so, can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), recreate the error, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly, please send the log file with the ticket reference GH-14694 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.

**Comment by KonaBill** [comment]
This issue doesn’t seem to happen now with the latest release.Thanks,William ModesittOn Jul 11, 2023, at 1:35 AM, Laura ***@***.***> wrote:﻿
I can't reproduce the described behavior on my side. Does this issue persist on your side within the latest Cyberduck version?
If so, can you please enable debug logging, recreate the error, and send us the log file afterward? If you don't like to see sensitive data to be shared publicly, please send the log file with the ticket reference GH-14694 to ***@***.***, otherwise attach it here.
Sidenote: If you want to share the log file here, make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.
