### ISSUE TITLE
Connection issues on a PC running Windows 11

### ISSUE THREAD

**Issue by Dragon6564** [iterate-ch/cyberduck#14716]
I've been using CyberDuck for a few years now. I use it with the same FTP server every day. Today, I can connect to the server, go to different folders and such, but when I try to send/download anything, the program freezes, send s a report to Microsoft, then tells me to close the program. I used it just fine yesterday. I just installed the newest update, but that has had no effect. Any ideas? I really need an FTP client that works, as I work from home and need to place/download a lot of files.
Thanks for your help.

**Comment by tatze96** [comment]
Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), re-create the described behavior, and send us the log file afterward? Also, please attach the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) if any are available.

If you don't like to see sensitive data to be shared publicly, please send the log files with the ticket reference GH-14716 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log files here, make sure to attach them through the GitHub web interface, as they wouldn't be visible to us otherwise.

**Comment by dkocher** [comment]
Duplicate for #12676.
