### ISSUE TITLE
Support streaming video files through FTP?

### ISSUE THREAD

**Issue by FezVrasta** [iterate-ch/cyberduck#14896]
**Is your feature request related to a problem? Please describe.**
I have a media server that is accessible through FTP over WAN. I would like to be able to start playing a video without having to download the whole file first.

**Describe the solution you'd like**
Ideally Cyberduck should allow to start streaming a video without having downloaded it completely first. Dedicated media players support FTP streaming (VLC, Infuse).

Most FTP servers support random access / seeking through a REST endpoint, so it should be feasible to even support that if you wanted to go the extra mile.

Alternatively, you could support a minimal functionality where pre-defined media players can be selected to open the FTP URL in order to let them handle the streaming.

**Describe alternatives you've considered**
The only alternative is to use VLC (that is not particularly good at this, it has issues listing directories and files and it's very slow) or use Infuse (which works great but it's not available for free).

**Comment by tatze96** [comment]
Cyberduck isn't a streaming application. It is solely a client application for file editing and management. Additionally, many applications need to know the length of the file before they can open it, which is why a streaming feature would make little sense.

You can try out [Mountain Duck](https://mountainduck.io/) with the *Online* mode selected and deactivated [buffering](https://docs.cyberduck.io/mountainduck/preferences/#enable-buffering) to see if this suits your use case.

**Comment by FezVrasta** [comment]
Do you think the suggested minimal functionality would be out of scope as well? It looks reasonable to me.

> Alternatively, you could support a minimal functionality where pre-defined media players can be selected to open the FTP URL in order to let them handle the streaming.

**Comment by dcrystalj** [comment]
I ended up with:

added smpv function to zshrc:
```
smpv() {
 P=( $( echo "$1" | cut -d "," -f 1 ) )
 mpv sftp://user@85.190.55.11:22:$P
}
```

then in cyberduck `cmd+c` on file to copy path.
and in terminal write `smpv` with `cmd+v` to start streaming video
