### ISSUE TITLE
Cyberduck extremely slow to download lots of small files from S3

### ISSUE THREAD

**Issue by lucaskoensgen** [iterate-ch/cyberduck#15208]
**Description**
When attempting to use Cyberduck to download a whole folder from S3 that contains a large number of files (~50k) the application takes an incredibly long time. This is to the point where it becomes basically non-functional. 

The individual file size need not be big for this problem to arise - a folder containing under 1GB of data in small files (<20KB each) has repeatedly taken me over an hour and a half to download.

All of the actions that normally appear in the Transfers pop up window take an incredibly long time (ie. Prepare, Downloading etc.) but progress through the list of files as per usual.

**To Reproduce**
1. Enable segmented downloads with multiple connections per file
2. Have a folder in an S3 bucket with a large number of files (>50k)
3. Have these files be small (<20kB each)
4. Download the whole folder  

**Expected behavior**
The files should download in a reasonable time frame with speeds similar to using AWS CLI

**Desktop:**
 - OS: Windows 11 Pro (10.0.2261)
 - Version 8.5.5

**Comment by tatze96** [comment]
This is currently expected behavior, given that you're using an encrypted (HTTPS) connection to connect to your S3 server. We're already working on a solution but can't provide a timeframe for when this will be fixed.

I'll close this ticket as a duplicate for #14909. We'll post any updates regarding the solution there.

**Comment by warrenlain** [comment]
I'm currently encountering this as I do a manual backup of my website, which is not necesssarily large, but is comprised of many small files. It's been preparing to download it for the past four hours now, and the estimated size has slowly grown over that period (9GB now). I'm okay with leaving it on overnight but I'm not sure even that will be enough time. I'm connected over SFTP if that context helps, and I'm using what should be the latest Mac OS version of Cyberduck, Version 9.1.3 (42945).

Has Cyberduck fixed this yet and I'm just doing this wrong (dragging the whole group of top level folders), or is this still expected behavior?
