### ISSUE TITLE
KeyExchange certificate check failed

### ISSUE THREAD

**Issue by acrux42** [iterate-ch/cyberduck#15354]
Suddenly, connection to a remote server via sftp using a private key stopped working with this exception:

```
KeyExchange certificate check failed: Hostname <server name> doesn't match any of the principals: <list of IPs of the server probably>
```

Form the log, it seems the error is from net.schmizz.sshj.transport.TransportImpl.

The same error appears when using cyberduck, but Filezilla works.

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version 4.15.1 (21679)
I think between the last time it worked and now I updated Mountain Duck, but not sure.

Is there some setting to disable this check or would it pe possible do downgrade mountain duck to a version where it works properly?

**Comment by tatze96** [comment]
To investigate the error further, we need the following information:
- A screenshot of the error message.
- The log file of Cyberduck.

For the log file [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), recreate the issue, and send us the log file afterward. If you don't like to see sensitive data to be shared publicly, please send the log file with the ticket reference GH-15354 to support@cyberduck.io, otherwise attach it here.

**Sidenote**: If you want to share the log file and screenshot here, make sure to attach them through the GitHub web interface, as they wouldn't be visible to us otherwise.

Regarding reverting to a previous version:
You can revert to a previous version of Cyberduck or Mountain Duck by removing the current application file from the _Applications_ folder and copying the application file of the previous version into it afterward. Ensure that Mountain Duck or, respectively, Cyberduck isn't running while doing so.

Previous versions of [Cyberduck](https://cyberduck.io/changelog/) and [Mountain Duck](https://mountainduck.io/changelog/) can be downloaded from their respective changelog pages.

**Comment by yhao9s9** [comment]
Hi, I met the same issue. Here are the screenshot of the error message and the log file.
![Screenshot 2024-01-08 at 21 14 52](https://github.com/iterate-ch/cyberduck/assets/91327526/15b86d14-ce30-4940-b620-40b2c1a7fd7b)
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/13865918/cyberduck.log)
Could you help me to resolve it?
Thank you!

**Comment by helenwsung** [comment]
I've run into this same issue, is there any solution?

**Comment by Reginard** [comment]
Same issue here

macOS Sonoma 14.6.1 (23G93)
Version 9.0.1 (41941)

**Comment by dkocher** [comment]
Discussion in #16260.
