### ISSUE TITLE
Problem uploading folders with nested folders

### ISSUE THREAD

**Issue by ghost** [iterate-ch/cyberduck#15489]
**Describe the bug**
I Created an ARCHIVE bucket in  Google Cloud, enabled Cryptomator inside It with a password. When I upload a folder with nested folders, during the creation of the nested folders I receive an arror saying "File not found", but If I see the encrypyted folders on the bucket using the browser I understand that the folder with the first sub-folder is created. From this moment, I cannot access anymore with Cyberduck and I have to delete these folders manually on the bucket using the browser

**To Reproduce**

**Expected behavior**
I expect that If I upload folders with sub-folders they are correctly created and populated

**Screenshots**
Screenshot attached
<img width="1205" alt="1" src="https://github.com/iterate-ch/cyberduck/assets/105058362/80759a93-1125-4819-a00f-10bd270c81d0">
<img width="879" alt="2" src="https://github.com/iterate-ch/cyberduck/assets/105058362/0f3fdae0-b41b-4a48-ba9b-c06a0a3f7536">

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 23H2

**Log Files**
Log file attached
[cyberduck.zip](https://github.com/iterate-ch/cyberduck/files/13758697/cyberduck.zip)

**Additional context**
It seems a problem about Cryptomator, infact the same operation without It works fine

**Comment by dkocher** [comment]
Regression from 2ffea63c with single `Directory` feature shared creating for creating multiple folders in a transfer. This causes failures for protocols using file based markers for pseudo directories because the injected encrypting writer is cached [^1] and reused falsely for plaintext intermediate folders.

[^1]: https://github.com/iterate-ch/cyberduck/blob/35dfb14d9764a473c9cdc21aaaa05cfda8d71775/cryptomator/src/main/java/ch/cyberduck/core/cryptomator/features/CryptoDirectoryV7Feature.java#L78C1-L79C1
