### ISSUE TITLE
S3 metadata missing in 8.8.0+

### ISSUE THREAD

**Issue by jabeler** [iterate-ch/cyberduck#15742]
**Describe the bug**
In 8.8.0+ parts of the existing S3 metadata cannot be viewed, and making changes to files will overwrite/remove the existing metadata. 

**To Reproduce**

View the metadata for a file stored in S3 in 8.7.2 and compare it to what is shown in 8.8.0.

**Screenshots**

**Version 8.7.2**
![872](https://github.com/iterate-ch/cyberduck/assets/31429009/7de9e62c-b274-4f05-b1f8-724635309d4c)

**Version 8.8.0**
![880](https://github.com/iterate-ch/cyberduck/assets/31429009/860e0552-dfe8-4554-9692-88e27168d653)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 14.4

**Comment by dkocher** [comment]
Regression from 51d46a06fb97daeae5a81d7ceca4f04c63954a7d.

**Comment by drbuckyballs** [comment]
We have discovered a similar issue. I don't believe it's resolved. 

When copying multiple files for example .jpg and .mp4 together from dropbox to s3 bucket.

then cyberduck just changes the metadata values to octet/stream for all files instead of maintaining it's original metadata values which should have been image/jpeg for the jpg files. That's a big issue for us.

Issue on windows and latest cyberduck version.
