### ISSUE TITLE
On Windows 11 inability to select Notepad++ as default editor

### ISSUE THREAD

**Issue by luctrudel** [iterate-ch/cyberduck#16387]
When I try to change preferences editor no file dialog to select my main editor Notepad++

Other applications are listed without needing to browse to.

But if you need to select other there's no file dialog to let you select it.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Editor'
3. Select 'Choose'
4. Notice Nothing Happens then
5. Close 'Preferences'
6. In the main bar Next to editor button, Dropdown triangle
7. Select 'Choose'
8. File dialog option says 'Select an App to open .html' file
9. There's only the option to use this one time

**Expected behavior**
I would expect the app the see from my system that .txt files are usually opened with notepad++ and offer this as one of the options.
If not that, at minimum, I would expect the file dialog to be invoked when I click step 3 'Choose' the .exe of my editor and then to save and persist in memory.

**Screenshots**
<img width="646" alt="File Dialog Just one time option not save as default" src="https://github.com/user-attachments/assets/1a90e123-3f3c-40d1-8056-5d88e14af1cd">
<img width="646" alt="bug select editor notepad++_not-prepopulated" src="https://github.com/user-attachments/assets/7c48021d-c486-4e64-9007-88e90b097626">
<img width="646" alt="bug select editor notepad++_not-prepopulated+Choose2" src="https://github.com/user-attachments/assets/80c0972c-ae62-40c0-b55d-c0fa36338967">
<img width="646" alt="bug select editor notepad++_not-prepopulated+Choose" src="https://github.com/user-attachments/assets/46d9fa8a-74de-42f7-8876-7e1fb845efe5">
<img width="643" alt="bug select editor" src="https://github.com/user-attachments/assets/a19d0e4a-8f25-4ac0-9267-e04215a33968">

<img width="256" alt="Initiate - File Dialog Just one time option not save as default" src="https://github.com/user-attachments/assets/56c47358-ed89-4763-94dd-7246bc20d4df">

**Desktop (please complete the following information):**
Windows 11. 22631.4169

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/17179640/cyberduck.log)

**Additional context**
I usually have a bit of French and English as I live in Canada.

**Comment by AliveDevil** [comment]
Separate things here.
We had a regression, where the default editor wouldn't persist: #16362 - fixed in current Snapshot.
The choose button should'nt be there … missed that, while reviewing the editors functionality.

I can confirm, that Notepad++ isn't selectable when intalled on the system - this might be an issue with Notepad++, but I'm not entirely sure.

Reason I suspect this is more an issue with Notepad++, than Cyberduck: We are using the Win32 function `SHAssocEnumHandlers` to enumerate all applications that can edit an empty file name (i.e. Windows should list all applications which registered themselves for "").
I'll check, whether we can provide guidance on registering Notepad++ as a default visible editor on Cyberduck.

**Comment by AliveDevil** [comment]
Sidenote here: When using "Open with" we are using the [system "Open with"-dialog](https://learn.microsoft.com/windows/win32/api/shlobj_core/nf-shlobj_core-shopenwithdialog), which got severly cut down starting in Windows 10:
> Starting in Windows 10, the OAIF_ALLOW_REGISTRATION, OAIF_FORCE_REGISTRATION, and OAIF_HIDE_REGISTRATION flags will be ignored by SHOpenWithDialog. The Open With dialog box can no longer be used to change the default program used to open a file extension. You can only use SHOpenWithDialog to open a single file.

(ibid)
